// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(KingdomContext))]
    [Migration("20210620092203_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GroupName");

                    b.Property<int>("GroupSize")
                        .HasColumnType("int")
                        .HasColumnName("GroupSize");

                    b.Property<string>("GroupType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GroupType");

                    b.Property<int?>("KingdomID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KingdomID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("WebAPI.Models.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("HeroClass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HeroClass");

                    b.Property<string>("HeroName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HeroName");

                    b.Property<int>("HeroOrder")
                        .HasColumnType("int")
                        .HasColumnName("HeroOrder");

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("WebAPI.Models.Kingdom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("King")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("King");

                    b.Property<string>("KingdomCapitol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KingdomCapitol");

                    b.Property<string>("KingdomName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KingdomName");

                    b.HasKey("ID");

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("WebAPI.Models.Group", b =>
                {
                    b.HasOne("WebAPI.Models.Kingdom", "Kingdom")
                        .WithMany("Groups")
                        .HasForeignKey("KingdomID");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("WebAPI.Models.Hero", b =>
                {
                    b.HasOne("WebAPI.Models.Group", "Group")
                        .WithMany("Heroes")
                        .HasForeignKey("GroupID");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebAPI.Models.Group", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("WebAPI.Models.Kingdom", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
